name: ${mcperf.name}
version: ${project.version}
description: 'Performance and security utility'
load: STARTUP
author: Zenexer
main: com.earth2me.mcperf.MCPerfPlugin
loadbefore:
  # We need to load before all other plugins, if possible.  This ensures that we intercept commands and chat
  # before everything else.
  - DeluxeChat
  - DeluxeTags
  - MooPermissions
  - MooPerms
  - GroupManager
  - Vault
  - Essentials
  - MilkyKore
  - TownyChat
  - Towny
  - zPermissions
  - EssentialsChat
  - Skript
  - mcMMO
  - Buycraft
  - WorldGuard
  - WorldEdit
  - floAuction
  - Factions
  - RedeemMCMMO
  - NoCheatPlus
  - CompatNoCheatPlus
  - Multiverse-Core
  - PlotSquared
  - BanManager
  - AutoMessage
  - LilyPad-Connect
  - SurvivalGames
  - Puffix
  - kits
  - AntiAutoSoup
  - ColoredTags
  - CleanroomGenerator
  - AsyncWorldEditInjector
  - PistonBlocker
  - WorldBorder
  - Lockette
  - AsyncWorldEdit
  - EchoPet
  - SkyBlock
  - LilyPad-Portal
  - WhatIsIt
  - LibsDisguises
  - JustShop
  - SilkSpawners
  - XenLink
  - WorldReset
  - PlotMe-DefaultGenerator
  - CowClash
  - AntiAura
  - VoidWorld
  - SpectatorPlus
  - ScheduledRestarter
  - Tab
  - SkyWarsReloaded
  - HolographicDisplays
commands:
  mcperf:
    description: "Views version and reloads MCPerf's configuration from disk."
    permission: mcperf.reload
  chans:
    description: "Displays the plugin channels that a user's client has registered."
    permission: mcperf.chans
    usage: '/<command> * | <player> [player]...'
  screen:
    description: "Starts an interactive screening process for hack clients."
    permission: mcperf.screen
    usage: '/<command> * | <player> [player]...'
  proxy:
    description: "Checks a player for signs of proxy/VPN usage."
    permission: mcperf.proxy
    usage: '/<command> <player>'
    aliases:
      - vpn
permissions:
  mcperf.*:
    description: 'Full MCPerf access'
    children:
      mcperf.reload: true
      mcperf.chans: true
      mcperf.chans.multiple: true
      mcperf.chans.all: true
      mcperf.chans.*: true
      mcperf.screen: true
      mcperf.screen.multiple: true
      mcperf.screen.all: true
      mcperf.screen.*: true
      mcperf.receivealerts: true
      mcperf.proxy: true
  mcperf.reload:
    description: 'Gives access to /mcperf reload; used to reload configuration'
  mcperf.chans.*:
    description: 'Full /chans access'
    children:
      mcperf.chans: true
      mcperf.chans.multiple: true
      mcperf.chans.all: true
  mcperf.chans:
    description: 'Gives access to /chans; used to check what channels a user has registered'
  mcperf.chans.multiple:
    description: 'Gives access to /chans with more than one argument'
  mcperf.chans.all:
    description: 'Gives access to /chans *; used to scan the channels of every player on the server'
  mcperf.screen:
    description: 'Gives access to /screen; used to screen players for hack clients'
  mcperf.screen.multiple:
    description: 'Gives access to /screen with more than one argument'
  mcperf.screen.all:
    description: 'Gives access to /screen *; used to screen every player on the server'
  mcperf.screen.*:
    description: 'Full /screen access'
    children:
      mcperf.screen: true
      mcperf.screen.multiple: true
      mcperf.screen.all: true
  mcperf.receivealerts:
    description: 'Receive op notices about cheaters and similar discrepancies'
  mcperf.proxy:
    description: 'Gives access to /proxy; used to scan users for signs of proxy/VPN usage'