name: MCPerf-Performance
version: 1.2.0
description: 'Performance and security utility'
load: STARTUP
author: Zenexer
main: com.earth2me.mcperf.MCPerfPlugin
loadbefore:
  # We need to load before all other plugins, if possible.  This ensures that we intercept commands and chat
  # before everything else.
  - DeluxeChat
  - DeluxeTags
  - MooPermissions
  - MooPerms
  - GroupManager
  - Vault
  - Essentials
  - MilkyKore
  - TownyChat
  - Towny
  - zPermissions
  - EssentialsChat
  - Skript
  - mcMMO
  - Buycraft
  - WorldGuard
  - WorldEdit
  - floAuction
  - Factions
  - RedeemMCMMO
  - NoCheatPlus
  - CompatNoCheatPlus
  - Multiverse-Core
  - PlotSquared
  - BanManager
  - AutoMessage
  - LilyPad-Connect
  - SurvivalGames
  - Puffix
  - kits
  - AntiAutoSoup
  - ColoredTags
  - CleanroomGenerator
  - AsyncWorldEditInjector
  - PistonBlocker
  - WorldBorder
  - Lockette
  - AsyncWorldEdit
  - EchoPet
  - SkyBlock
  - LilyPad-Portal
  - WhatIsIt
  - LibsDisguises
  - JustShop
  - SilkSpawners
  - XenLink
  - WorldReset
  - PlotMe-DefaultGenerator
  - CowClash
  - AntiAura
  - VoidWorld
  - SpectatorPlus
  - ScheduledRestarter
  - Tab
  - SkyWarsReloaded
  - HolographicDisplays
commands:
  mcperf:
    description: "Views version and reloads MCPerf's configuration from disk."
    permission: mcperf.reload
permissions:
  mcperf.*:
    description: 'Full MCPerf access'
    children:
      mcperf.reload: true
      mcperf.receivealerts: true
  mcperf.reload:
    description: 'Gives access to /mcperf reload; used to reload configuration'
  mcperf.receivealerts:
    description: 'Receive op notices about cheaters and similar discrepancies'