entityManager:
  nearbyChunkRadius: 1
  nearbyItemLimit: 400
  nearbyCreatureLimit: 200
  worldItemLimit: 3000
  worldCreatureLimit: 2000
validityManager:
  enabled: false
  maxLoreLines: 5
  maxLoreLineLength: 127
  maxNameLength: 63
  basicUnicodeAllowed: true
  supplementaryUnicodeAllowed: true
  privateUnicodeAllowed: true
  linebreakUnicodeAllowed: false
  controlUnicodeAllowed: false
  unusualWhitespaceUnicodeAllowed: false
  nullCharAllowed: false
  escapeCharAllowed: false
  formattingAllowed: true
  crazyTextAllowed: true
  enchantmentCheckingEnabled: false
  potionCheckingEnabled: false
  splashPotionCheckingEnabled: false
  splashPotionsBanned: false
  zeroQuantityBanned: false
screeningManager:
  enabled: false
  gracePeriod: 20  # Seconds