entityManager:
  nearbyChunkRadius: 1
  nearbyItemLimit: 400
  nearbyCreatureLimit: 200
  worldItemLimit: 3000
  worldCreatureLimit: 2000
validityManager:
  maxLoreLines: 5
  maxLoreLineLength: 64
  maxNameLength: 64
  fullUnicodeAllowed: false
  enchantmentCheckingEnabled: false